# Environment variable UID is used for the container's user's UID.
# If missing or empty, Dockerfile uses a default (probably 1000).
# This is to let access the container to the host's volume ./volumes/.
# Note that bash's UID is not exported. So you may build with
#
# (export UID && docker-compose build)

version: '2'

services:
  master:
    build:
      context: build
      args:
        - UID
    image: jobscheduler
    container_name: jobscheduler-master
    command: ["master", "-java-option=-Xmx500m"]
    networks:
    - default
    ports:
    - "127.0.0.1:4444:4444"
    working_dir: /var/opt/jobscheduler/master/data
    volumes:
      - ./volumes/master:/var/opt/jobscheduler/master
  agent-1:
    image: jobscheduler
    container_name: jobscheduler-agent-1
    command: ["agent", "-java-option=-Xmx100m"]
    hostname: agent-1
    working_dir: /var/opt/jobscheduler/agent/data
    volumes:
      - ./volumes/agent-1:/var/opt/jobscheduler/agent
  agent-2:
    image: jobscheduler
    container_name: jobscheduler-agent-2
    command: ["agent", "-java-option=-Xmx100m"]
    hostname: agent-2
    working_dir: /var/opt/jobscheduler/agent/data
    volumes:
      - ./volumes/agent-2:/var/opt/jobscheduler/agent
