# Environment variable UID is used for the container's user's UID.
# If missing or empty, Dockerfile uses a default (probably 1000).
# This is to let access the container to the host's volume ./volumes/.
# Note that bash's UID is not exported. So you may build with
#
# (export UID && docker-compose build)

version: "3"

services:
  master:
    build:
      context: build
      args:
        - UID
    image: jobscheduler
    container_name: jobscheduler-master
    command: ["master", "-J-Xmx200m"]
    hostname: master
    networks:
    - default
    ports:
    - "127.0.0.1:4444:4444"
    working_dir: /var/opt/jobscheduler/master/data
    volumes:
      - ./volumes/master/config:/var/opt/jobscheduler/master/config:ro
      - ./volumes/master/data:/var/opt/jobscheduler/master/data:delegated
    stop_grace_period: 30s
    restart: unless-stopped

  provider:
    image: jobscheduler
    container_name: jobscheduler-provider
    command: ["provider", "-J-Xmx100m", "-master-uri=http://master:4444"]
    hostname: provider
    working_dir: /var/opt/jobscheduler/provider/data
    volumes:
      - ./volumes/provider/config:/var/opt/jobscheduler/provider/config:ro
      - ./volumes/provider/data:/var/opt/jobscheduler/provider/data:delegated
    restart: unless-stopped

  agent-1:
    image: jobscheduler
    container_name: jobscheduler-agent-1
    command: ["agent", "-J-Xmx200m"]
    hostname: agent-1
    working_dir: /var/opt/jobscheduler/agent/data
    volumes:
      - ./volumes/agent-1/config:/var/opt/jobscheduler/agent/config:ro
      - ./volumes/agent-1/data:/var/opt/jobscheduler/agent/data:delegated
    stop_grace_period: 30s
    restart: unless-stopped

  agent-2:
    image: jobscheduler
    container_name: jobscheduler-agent-2
    command: ["agent", "-J-Xmx200m"]
    hostname: agent-2
    working_dir: /var/opt/jobscheduler/agent/data
    volumes:
      - ./volumes/agent-2/config:/var/opt/jobscheduler/agent/config:ro
      - ./volumes/agent-2/data:/var/opt/jobscheduler/agent/data:delegated
    stop_grace_period: 30s
    restart: unless-stopped
