#!/usr/bin/env bash
set -e

cd "$(dirname "$0")"
export SBT_OPTS="-Dlog4j.configurationFile=project/log4j2.xml $SBT_OPTS"
export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=512M -XX:MetaspaceSize=256M -Xms2G -Xmx2G"
sbt -batch "; clean; build"
