#!/usr/bin/env bash
set -e

cd "${0%/*}"
rm -f target/build.log
if [ "$OSTYPE" = "cygwin" ]; then
  exec cmd /c sbt-batch.cmd "$@"
else
  # See also files .sbtopts and .javaopts
  export JAVA_OPTS="-Dsbt.log.noformat=true $JAVA_OPTS"
  exec sbt -batch "$@"
fi
