# See https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'JS7'
    scheme: https
    tls_config:
      ca_file: "/var/opt/prometheus/private/CA.crt"
      cert_file: "/var/opt/prometheus/private/prometheus.crt"
      key_file: "/var/opt/prometheus/private/prometheus.key"
    static_configs:
      - targets:
        - js7-controller:4443
        - js7-provider:4443
        - js7-proxy:4443
        - js7-proxy-b:4443
