version: '2'
services:
  master:
    build: .
    image: jobscheduler
    container_name: jobscheduler-master
    command: ["master", "-java-option=-Xmx200m"]
    networks:
    - default
    ports:
    - "4444:4444"
    volumes:
      - master:/var/lib/jobscheduler/master
    working_dir: /var/lib/jobscheduler/master
  agent-1:
    build: .
    image: jobscheduler
    container_name: jobscheduler-agent-1
    command: ["agent", "-java-option=-Xmx100m"]
    hostname: agent-1
    volumes:
      - agent-1:/var/lib/jobscheduler/agent
    working_dir: /var/lib/jobscheduler/agent
  agent-2:
    build: .
    image: jobscheduler
    container_name: jobscheduler-agent-2
    command: ["agent", "-java-option=-Xmx100m"]
    hostname: agent-2
    volumes:
      - agent-2:/var/lib/jobscheduler/agent
    working_dir: /var/lib/jobscheduler/agent
volumes:
  master:
  agent-1:
  agent-2:
