version: '2'
services:
  master:
    build: build
    image: jobscheduler
    container_name: jobscheduler-master
    command: ["master"]
    networks:
    - default
    ports:
    - "127.0.0.1:4444:4444"
    working_dir: /var/opt/jobscheduler/master
    volumes:
      - ./volumes/master/data:/var/opt/jobscheduler/master
  agent-1:
    build: build
    image: jobscheduler
    container_name: jobscheduler-agent-1
    command: ["agent", "-java-option=-Xmx100m"]
    hostname: agent-1
    working_dir: /var/opt/jobscheduler/agent
    volumes:
      - ./volumes/agent-1/data:/var/opt/jobscheduler/agent
  agent-2:
    build: build
    image: jobscheduler
    container_name: jobscheduler-agent-2
    command: ["agent", "-java-option=-Xmx100m"]
    hostname: agent-2
    working_dir: /var/opt/jobscheduler/agent
    volumes:
      - ./volumes/agent-2/data:/var/opt/jobscheduler/agent
