services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    cpus: 0.5
    user: 1000:1000 # The volumes/prometheus directory will be accessed with this UID:GID
    volumes:
      - ./volumes/prometheus/config/private:/var/opt/prometheus/private:ro
      - ./volumes/prometheus/etc:/etc/prometheus:ro
      - ./volumes/prometheus/data:/prometheus:delegates
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    cpus: 0.5
    user: 1000:1000 # The volumes/grafana directory will be accessed with this UID:GID
    ports:
      - "0.0.0.0:3000:3000" # Publicly accessible !!!
    #environment:
    #  - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volumes/grafana/:/var/lib/grafana
    restart: unless-stopped

networks:
  default:
    name: js7
