# Environment variable UID is used for the container's user's UID.
# If missing or empty, Dockerfile uses a default (probably 1000).
# This is to let access the container to the host's volume ./volumes/.
# Note that bash's UID is not exported. So you may build with
#
# (export UID && docker-compose build)

version: "3.2"

services:
  controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-controller
    hostname: controller
    command: ["js7-controller", "-J-Xmx200m"]
    networks:
    - default
    ports:
    - "127.0.0.1:4443:4443"
    - "127.0.0.1:4444:4444"
    working_dir: /home/js7
    volumes:
      - ./volumes/controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/controller/data/cache:/var/opt/js7/controller/data/cache:delegated
      - ./volumes/controller/data/logs:/var/opt/js7/controller/data/logs:delegated
      - ./volumes/controller/data/state:/var/opt/js7/controller/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  backup-controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-backup-controller
    hostname: backup-controller
    command: ["js7-controller", "-J-Xmx200m"]
    networks:
    - default
    #ports:
    #Does not work for Docker 2.2.3.0 MacOS:  - "127.0.0.2:4444:4444"
    working_dir: /home/js7
    volumes:
      - ./volumes/backup-controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/backup-controller/data/cache:/var/opt/js7/controller/data/cache:delegated
      - ./volumes/backup-controller/data/logs:/var/opt/js7/controller/data/logs:delegated
      - ./volumes/backup-controller/data/state:/var/opt/js7/controller/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  provider:
    image: js7
    container_name: js7-provider
    hostname: provider
    command: ["js7-provider", "-J-Xmx100m", "--controller-uri=https://controller:4443"]
    working_dir: /home/js7
    volumes:
      - ./volumes/provider/config:/var/opt/js7/provider/config:ro
      - ./volumes/provider/data/cache:/var/opt/js7/provicer/data/cache:delegated
      - ./volumes/provider/data/logs:/var/opt/js7/provicer/data/logs:delegated
      - ./volumes/provider/data/state:/var/opt/js7/provicer/data/state:delegated
    restart: unless-stopped

  subagent-1-a:
    image: js7
    container_name: js7-subagent-1-a
    hostname: subagent-1-a
    command: ["js7-subagent", "-J-Xmx200m"]
    working_dir: /home/js7
    volumes:
      - ./volumes/subagent-1-a/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1-a/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1-a/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1-a/data/state:/var/opt/js7/agent/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  subagent-1-b:
    image: js7
    container_name: js7-subagent-1-b
    hostname: subagent-1-b
    command: ["js7-subagent", "-J-Xmx200m"]
    working_dir: /home/js7
    volumes:
      - ./volumes/subagent-1-b/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1-b/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1-b/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1-b/data/state:/var/opt/js7/agent/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  subagent-2-a:
    image: js7
    container_name: js7-subagent-2-a
    hostname: subagent-2-a
    command: ["js7-subagent", "-J-Xmx200m"]
    working_dir: /home/js7
    volumes:
      - ./volumes/subagent-2-a/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-2-a/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-2-a/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-2-a/data/state:/var/opt/js7/agent/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped
