# Environment variable UID is used for the container's user's UID.
# If missing or empty, Dockerfile uses a default (probably 1000).
# This is to let access the container to the host's volume ./volumes/.
# Note that bash's UID is not exported. So you may build with
#
# (export UID && docker-compose build)

version: "3.2"

services:
  controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-controller
    command: ["js7-controller", "-J-Xmx200m"]
    hostname: controller
    networks:
    - default
    ports:
    - "127.0.0.1:4443:4443"
    - "127.0.0.1:4444:4444"
    working_dir: /var/opt/js7/controller/data
    volumes:
      - ./volumes/controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/controller/data:/var/opt/js7/controller/data:delegated
    depends_on:
      - agent-1
      - agent-2
    stop_grace_period: 10s
    restart: unless-stopped

  backup-controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-backup-controller
    command: ["js7-controller", "-J-Xmx200m"]
    hostname: backup-controller
    networks:
    - default
    #ports:
    #Does not work for Docker 2.2.3.0 MacOS:  - "127.0.0.2:4444:4444"
    working_dir: /var/opt/js7/controller/data
    volumes:
      - ./volumes/backup-controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/backup-controller/data:/var/opt/js7/controller/data:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  provider:
    image: js7
    container_name: js7-provider
    command: ["js7-provider", "-J-Xmx100m", "--controller-uri=https://controller:4443"]
    hostname: provider
    working_dir: /var/opt/js7/provider/data
    volumes:
      - ./volumes/provider/config:/var/opt/js7/provider/config:ro
      - ./volumes/provider/data:/var/opt/js7/provider/data:delegated
    restart: unless-stopped

  agent-1:
    image: js7
    container_name: js7-agent-1
    command: ["js7-agent", "-J-Xmx200m"]
    hostname: agent-1
    working_dir: /var/opt/js7/agent/data
    volumes:
      - ./volumes/agent-1/config:/var/opt/js7/agent/config:ro
      - ./volumes/agent-1/data:/var/opt/js7/agent/data:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  agent-2:
    image: js7
    container_name: js7-agent-2
    command: ["js7-agent", "-J-Xmx200m"]
    hostname: agent-2
    working_dir: /var/opt/js7/agent/data
    volumes:
      - ./volumes/agent-2/config:/var/opt/js7/agent/config:ro
      - ./volumes/agent-2/data:/var/opt/js7/agent/data:delegated
    stop_grace_period: 10s
    restart: unless-stopped
