# Required environment variables: UID, TZ
#
# Environment variable UID is used for the container's user's UID.
# If missing or empty, Dockerfile uses a default (probably 1000).
# This is to let access the container to the host's volume ./volumes/.
# Note that bash's UID is not exported. So you may build with
#
# (export UID && docker-compose build)

services:
  controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-controller
    hostname: js7-controller
    command: ["js7-controller", "--arg0=js7-controller", "-J-Xmx200m"]
    networks:
    - default
    ports:
    - "127.0.0.1:4443:4443"
    - "127.0.0.1:4444:4444"
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/controller/data/cache:/var/opt/js7/controller/data/cache:delegated
      - ./volumes/controller/data/logs:/var/opt/js7/controller/data/logs:delegated
      - ./volumes/controller/data/state:/var/opt/js7/controller/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  backup-controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-backup-controller
    hostname: js7-backup-controller
    command: ["js7-controller", "--arg0=js7-backup-controller", "-J-Xmx200m"]
    networks:
    - default
    #ports:
    #Does not work for Docker 2.2.3.0 macOS:  - "127.0.0.2:4444:4444"
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/backup-controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/backup-controller/data/cache:/var/opt/js7/controller/data/cache:delegated
      - ./volumes/backup-controller/data/logs:/var/opt/js7/controller/data/logs:delegated
      - ./volumes/backup-controller/data/state:/var/opt/js7/controller/data/state:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  provider:
    image: js7
    container_name: js7-provider
    hostname: js7-provider
    command: ["js7-provider", "--arg0=js7-provider", "-J-Xmx100m", "--controller-uri=https://controller:4443"]
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/provider/config:/var/opt/js7/provider/config:ro
      - ./volumes/provider/data/cache:/var/opt/js7/provider/data/cache:delegated
      - ./volumes/provider/data/logs:/var/opt/js7/provider/data/logs:delegated
      - ./volumes/provider/data/state:/var/opt/js7/provider/data/state:delegated
    restart: unless-stopped

  cluster-watch:
    image: js7
    container_name: js7-cluster-watch
    hostname: js7-cluster-watch
    command: [
      "js7-cluster-watch",
      "--arg0=js7-cluster-watch",
      "-J-Xmx50m",
      "--cluster-watch-id=CLUSTER-WATCH",
      "--cluster-node-uri=https://controller:4443",
      "--cluster-node-uri=https://backup-controller:4443" ]
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/cluster-watch/config:/var/opt/js7/cluster-watch/config:ro
      - ./volumes/cluster-watch/data/cache:/var/opt/js7/cluster-watch/data/cache:delegated
      - ./volumes/cluster-watch/data/logs:/var/opt/js7/cluster-watch/data/logs:delegated
      - ./volumes/cluster-watch/data/state:/var/opt/js7/cluster-watch/data/state:delegated
    restart: unless-stopped

  cluster-watch-b:
    image: js7
    container_name: js7-cluster-watch-b
    hostname: js7-cluster-watch-b
    command: [
      "js7-cluster-watch",
      "--arg0=js7-cluster-watch-b",
      "-J-Xmx50m",
      "--cluster-watch-id=CLUSTER-WATCH-B",
      "--cluster-node-uri=https://controller:4443",
      "--cluster-node-uri=https://backup-controller:4443" ]
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/cluster-watch-b/config:/var/opt/js7/cluster-watch/config:ro
      - ./volumes/cluster-watch-b/data/cache:/var/opt/js7/cluster-watch/data/cache:delegated
      - ./volumes/cluster-watch-b/data/logs:/var/opt/js7/cluster-watch/data/logs:delegated
      - ./volumes/cluster-watch-b/data/state:/var/opt/js7/cluster-watch/data/state:delegated
    restart: unless-stopped
    depends_on:
      - cluster-watch # Delay start of this cluster-watch-b and give way to the other cluster-watch
    profiles:
      - dontStart # Non-existent profile

  subagent-1-a:
    image: js7
    container_name: js7-subagent-1-a
    hostname: js7-subagent-1-a
    command: ["js7-subagent", "--arg0=js7-subagent-1-a", "-J-Xmx200m"]
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/subagent-1-a/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1-a/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1-a/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1-a/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-1-a/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  subagent-1-b:
    image: js7
    container_name: js7-subagent-1-b
    hostname: js7-subagent-1-b
    command: ["js7-subagent", "--arg0=js7-subagent-1-b", "-J-Xmx200m"]
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/subagent-1-b/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1-b/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1-b/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1-b/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-1-b/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 10s
    restart: unless-stopped

  subagent-2-a:
    image: js7
    container_name: js7-subagent-2-a
    hostname: js7-subagent-2-a
    command: ["js7-subagent", "--arg0=js7-subagent-2-a", "-J-Xmx200m"]
    working_dir: /home/js7
    environment:
      - TZ=$TZ
    volumes:
      - ./volumes/subagent-2-a/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-2-a/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-2-a/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-2-a/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-2-a/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 10s
    restart: unless-stopped
    depends_on:
      - controller
