#!/usr/bin/env bash
set -euo pipefail

row=$(printf '.%.0s' {1..1000})   # 1000 times "."
for i in {1..1}; do
  echo "$row"
done

echo "$SCHEDULER_PARAM_HELLO  🔵"
sleep 1
echo "$SCHEDULER_PARAM_HELLO  🔵 🔵"
sleep 1
echo "$SCHEDULER_PARAM_HELLO  🔵 🔵 🔵"
sleep 1
echo "$SCHEDULER_PARAM_HELLO  🔵 🔵 🔵 🔵"
