#!/bin/sh
set -eu

# USAGE EXAMPLE
# build-with-docker/run sbt ";clean;test"

cd "${0%/*}"/../build-with-docker/..
user=build

if which podman >/dev/null 2>&1 && test "$(uname)" != "Darwin"; then
  docker=podman
  # For proper ownership of mounted volumes
  extras="--userns=keep-id"
else
  docker=docker
  extras=""
fi

# Let Docker not accumulate old images:
docker rmi js7-builder >/dev/null 2>&1 || true

( cd build-with-docker
  DOCKER_BUILDKIT=1 DOCKER_SCAN_SUGGEST=false $docker build --tag=js7-builder  .
)

$docker run \
  $extras \
  --volume=js7-builder:/home/$user/mount \
  --volume="$(pwd)":/home/$user/js7:Z,delegated \
  --workdir="/home/$user/js7" \
  --tty $(if tty -s; then echo "--interactive"; fi) \
  --hostname=js7-builder \
  --name=js7-builder \
  --rm \
  js7-builder \
  "$@"
