#!/bin/sh
set -eu

# USAGE EXAMPLE
# build-with-docker/run sbt ";clean;test"

cd "${0%/*}"/../build-with-docker/..
user=build

if which podman >/dev/null 2>&1 && test "$(uname)" != "Darwin"; then
  docker=podman
  # For proper ownership of mounted volumes
  extras="--userns=keep-id"
else
  docker=docker
  extras=""
fi

# Rebuild with fresh Linux only once per calendar day or when Dockerfile has changed
#
# In case jq is not available, or any other error,
# "-bash: jq: command not found" is shown and the image will be built
dockerDate="$(docker inspect js7-builder | jq -r '.[0].Identity.Build[0].CreatedAt' | sed s/null/0/ || echo 0)"
if expr "'$dockerDate'" '<' "'$(/bin/date -Ins -r build-with-docker/Dockerfile)'" >/dev/null \
|| expr "'$dockerDate'" '<' "'$(/bin/date -Ins -r "$0")'" >/dev/null \
|| expr "'$(echo "$dockerDate" | cut -c 1-10)'" '<' "'$(/bin/date -Idate)'" >/dev/null
then
  echo "🔹 Rebuild js7-builder Docker image"
  # Don't let Docker accumulate old images:
  docker rmi js7-builder >/dev/null 2>&1 || true

  $docker build --tag=js7-builder --network=host build-with-docker
fi

$docker run \
  $extras \
  --network=host \
  --volume=js7-builder:/home/$user/mount \
  --volume="$(pwd)":/home/$user/js7:Z,delegated \
  --workdir="/home/$user/js7" \
  --tty $(if tty -s; then echo "--interactive"; fi) \
  --hostname=js7-builder \
  --name=js7-builder \
  --rm \
  js7-builder \
  "$@"
