# Don't accept an expired X.509 certificates for an InventoryItem.
# "no" should be default, but isn't, due to JS-2219 and JS-2220.
js7.configuration.allow-expired-certificates = no

# Public for testAddOrders etc.
js7.web.server.auth.loopback-is-public = yes
#js7.web.server.auth.get-is-public = yes

js7.journal {
  cluster {
    node.is-backup = yes
  }
}

# Prefix of log files: js7.log, js7-debug.log (Docker example only)
js7.log.prefix = js7
