#! /bin/bash
# Generates a test TLS certificate
set -e

dir="$(dirname "$0")/../../../src/main/resources/com/sos/scheduler/engine/agent/test"
mkdir --parents "$dir"
cd $dir

privateKeystore="config/private/private-https.jks"
publicKeystore="https.jks"
alias=agent-https
keyPassword="jobscheduler"
storePassword="jobscheduler"
tmpCertFile="~https.cer"

rm -v --force "$privateKeystore" "$publicKeystore" "$tmpCertFile"

keytool -genkey \
  -alias "$alias" \
  -keyalg RSA \
  -keysize 1024 \
  -dname "CN=localhost, O=localhost, OU=Test" \
  -validity 3660 \
  -keypass "$keyPassword" \
  -storepass "$storePassword" \
  -keystore "$privateKeystore"

echo $(readlink --canonicalize $privateKeystore)
keytool -list -keystore "$privateKeystore" -deststorepass "$storePassword"

keytool -exportcert -noprompt -keystore "$privateKeystore" -alias "$alias" -file "$tmpCertFile" -storepass "$storePassword"
keytool -importcert -noprompt -alias "$alias" -file "$tmpCertFile" -keystore "$publicKeystore" -storepass "$storePassword"
echo
echo $(readlink --canonicalize $publicKeystore)
keytool -list -keystore "$publicKeystore" -deststorepass "$storePassword"
rm "$tmpCertFile"
