#! /bin/bash
# Generates a test TLS certificate
set -e

dir="$(dirname "$0")/../../../src/main/resources/com/sos/scheduler/engine/agent/test"
mkdir --parents "$dir"
cd $dir

distinguishedName="CN=localhost, O=Test"
privateKeystore="config/private/private-https.jks"
publicKeystore="agent-https.jks"
alias=agent-https
keyPassword="jobscheduler"
storePassword="jobscheduler"
publicCertFile="agent-https.pem"

rm -v --force "$privateKeystore" "$publicKeystore" "$publicCertFile"

keytool -genkey \
  -alias "$alias" \
  -dname "$distinguishedName" \
  -validity 3660 \
  -keyalg RSA \
  -keysize 1024 \
  -keypass "$keyPassword" \
  -keystore "$privateKeystore" \
  -storepass "$storePassword"

echo $(readlink --canonicalize $privateKeystore)
keytool -list -keystore "$privateKeystore" -deststorepass "$storePassword"

keytool -exportcert -rfc -noprompt \
  -keystore "$privateKeystore" \
  -storepass "$storePassword" \
  -alias "$alias" \
  -file "$publicCertFile"
keytool -importcert -noprompt \
  -file "$publicCertFile" \
  -keystore "$publicKeystore" \
  -storepass "$storePassword" \
  -alias "$alias"

keytool -list \
  -keystore "$publicKeystore" \
  -deststorepass "$storePassword"
echo
echo $distinguishedName
readlink --canonicalize "$privateKeystore" "$publicKeystore" "$publicCertFile"
