#! /bin/bash
# Generates a test TLS certificate
set -e

dir="$(dirname "$0")/../../../src/main/resources/com/sos/scheduler/engine/agent/test"
mkdir --parents "$dir"
cd $dir

distinguishedName="CN=localhost, O=Test"
privateKeystore="config/private/private-https.jks"
publicKeystore="agent-https.jks"
alias=agent-https
keyPassword="jobscheduler"
storePassword="jobscheduler"
certFile="agent-https.pem"

rm -v --force "$privateKeystore" "$publicKeystore" "$certFile"

keytool -genkey \
  -alias "$alias" \
  -keyalg RSA \
  -keysize 1024 \
  -dname "$distinguishedName" \
  -validity 3660 \
  -keypass "$keyPassword" \
  -storepass "$storePassword" \
  -keystore "$privateKeystore"

echo $(readlink --canonicalize $privateKeystore)
keytool -list -keystore "$privateKeystore" -deststorepass "$storePassword"

keytool -exportcert -rfc -noprompt -keystore "$privateKeystore" -alias "$alias" -file "$certFile" -storepass "$storePassword"
keytool -importcert -noprompt -alias "$alias" -file "$certFile" -keystore "$publicKeystore" -storepass "$storePassword"
keytool -list -keystore "$publicKeystore" -deststorepass "$storePassword"
echo
echo $distinguishedName
readlink --canonicalize $privateKeystore $publicKeystore $certFile
