#!/usr/bin/env bash
set -euo pipefail

HELLO="${HELLO:-}"

row=$(printf '.%.0s' {1..1000})   # 1000 times "."
for i in {1..1}; do
  echo "$row"
done

echo "$HELLO  🔵"
sleep 1
echo "$HELLO  🔵 🔵"
sleep 1
echo "$HELLO  🔵 🔵 🔵"
sleep 1
echo "$HELLO  🔵 🔵 🔵 🔵"
